[build]
  command = "npm run build"
  publish = "."

[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"

# Header rules to fix the Cross-Origin policy error
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Cross-Origin-Embedder-Policy = "require-corp"